### ISSUE TITLE
Kukkaði i brokkina.

### ISSUE THREAD

**Issue by kjassiturbo** [jessyjonsdottir/Stewart#3]
hæ kukkaði i brokina .vinsamlegast hjálpið þETTA ER EKKI GRÍN

**Comment by ivardor** [comment]
Kukka **MINNA** , vinna **MEIRA**...[ATH!](http://www.erfostudagur.is)

**Comment by kjassiturbo** [comment]
EKKI FOKA !!!!!

**Comment by kjassiturbo** [comment]
bunnað skeina mer i brokkina
